[ system ]
title = "SiO2 quadrupole example"
description = "Example of FCC lattice specification file with several atoms per lattice site"

nx = 60
ny = 60
nz = 1
spacing = 0.45
translate = [0.0, 0.0, 1.0]

[ atoms ]
residue = "SIO"
sites = [
    { name = "O1", dx = [0.0, 0.0, -0.151] },
    { name = "SI", dx = [0.0, 0.0,  0.0  ] },
    { name = "O2", dx = [0.0, 0.0, +0.151] },
]

[ layers ]
0   = "+"
